package clases;

import clases.Conejo;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rodri
 */
public class MenuInicio extends JFrame {

    private Conejo conejo;

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
        setLocationRelativeTo(null);
        conejo = new Conejo(labelConejo);
        KeyListener listener = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {      
            }
            @Override
            public void keyPressed(KeyEvent ke) {
                int code = ke.getExtendedKeyCode();
                switch (code) {
                    case KeyEvent.VK_ENTER:
                        conejo.accion();
                        break;
                    case KeyEvent.VK_UP:
                        conejo.moverArriba();
                        break;
                    case KeyEvent.VK_DOWN:
                        conejo.moverAbajo();
                        break;
                    default:
                        break;
                }
            }
            @Override
            public void keyReleased(KeyEvent ke) {
            }
        };
        addKeyListener(listener);
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConejo = new javax.swing.JLabel();
        botonSonido = new javax.swing.JButton();
        botonPuntaje = new javax.swing.JButton();
        botonCreditos = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonJugar = new javax.swing.JButton();
        labelMusica = new javax.swing.JLabel();
        labelSalir = new javax.swing.JLabel();
        labelJugar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelConejo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelConejo.setForeground(new java.awt.Color(239, 202, 38));
        labelConejo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConejo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/conejoDerecha.png"))); // NOI18N
        getContentPane().add(labelConejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 70, 70));

        botonSonido.setBackground(java.awt.Color.orange);
        botonSonido.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        botonSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenu.png"))); // NOI18N
        botonSonido.setText("SONIDO  ON");
        botonSonido.setBorder(null);
        botonSonido.setBorderPainted(false);
        botonSonido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSonido.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenuAccionado.png"))); // NOI18N
        botonSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSonidoActionPerformed(evt);
            }
        });
        getContentPane().add(botonSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 240, 70));

        botonPuntaje.setBackground(java.awt.Color.orange);
        botonPuntaje.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        botonPuntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenu.png"))); // NOI18N
        botonPuntaje.setText("PUNTAJES");
        botonPuntaje.setBorder(null);
        botonPuntaje.setBorderPainted(false);
        botonPuntaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPuntaje.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenuAccionado.png"))); // NOI18N
        botonPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntajeActionPerformed(evt);
            }
        });
        getContentPane().add(botonPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 240, 70));

        botonCreditos.setBackground(java.awt.Color.orange);
        botonCreditos.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        botonCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenu.png"))); // NOI18N
        botonCreditos.setText("CRÉDITOS");
        botonCreditos.setBorder(null);
        botonCreditos.setBorderPainted(false);
        botonCreditos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCreditos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenuAccionado.png"))); // NOI18N
        botonCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(botonCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 240, 70));

        botonSalir.setBackground(java.awt.Color.orange);
        botonSalir.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenu.png"))); // NOI18N
        botonSalir.setText("SALIR");
        botonSalir.setBorder(null);
        botonSalir.setBorderPainted(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenuAccionado.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 240, 70));

        botonJugar.setBackground(java.awt.Color.orange);
        botonJugar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        botonJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenu.png"))); // NOI18N
        botonJugar.setText("JUGAR");
        botonJugar.setBorder(null);
        botonJugar.setBorderPainted(false);
        botonJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonJugar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMenuAccionado.png"))); // NOI18N
        getContentPane().add(botonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 240, 70));

        labelMusica.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelMusica.setForeground(new java.awt.Color(239, 202, 38));
        labelMusica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMusica.setText("MÚSICA ON");
        getContentPane().add(labelMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 240, 70));

        labelSalir.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelSalir.setForeground(new java.awt.Color(239, 202, 38));
        labelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalir.setText("SALIR");
        getContentPane().add(labelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 240, 70));

        labelJugar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelJugar.setForeground(new java.awt.Color(239, 202, 38));
        labelJugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJugar.setText("JUGAR");
        getContentPane().add(labelJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 240, 70));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoMenu.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCreditosActionPerformed

    private void botonPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPuntajeActionPerformed

    private void botonSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSonidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSonidoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCreditos;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonPuntaje;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSonido;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel labelConejo;
    private javax.swing.JLabel labelJugar;
    private javax.swing.JLabel labelMusica;
    private javax.swing.JLabel labelSalir;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void keyTyped(KeyEvent ke) {
//        System.out.println("ke.getKeyChar()");
//        System.out.println("Se presiono una tecla");
//        if (ke.getKeyCode() == KeyEvent.VK_ESCAPE) {
//
//        } else if (ke.getKeyCode() == KeyEvent.VK_UP) {
//            conejo.moverArriba();
//            System.out.println("se apreto arriba");
//        } else if (ke.getKeyCode() == KeyEvent.VK_DOWN) {
//            conejo.moverAbajo();
//        }
//    }
//
//    @Override
//    public void keyPressed(KeyEvent ke) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//
//    @Override
//    public void keyReleased(KeyEvent ke) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
